name: recode_rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - openssl=1.1.1q
  - samtools=1.9
  - star=2.7.8a
  - fastqc=0.11.9
  - htseq=0.11.3
  - multiqc=1.12
  - trim-galore=0.6.7
  - sra-tools=2.11.0
  - nextflow=22.04.0
